name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 监听以 'v' 开头的标签，通常用来表示版本发布

jobs:
  build:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 环境下运行任务

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 设置 Node.js（如果是 Node.js 项目，可根据需要修改）
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # 使用 Node.js 14.x（根据项目需求修改）

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 打包项目（假设使用 npm script 打包，修改为实际的打包命令）
      - name: Build the project
        run: npm run build

  release:
    runs-on: ubuntu-latest  # 在 Ubuntu 环境下运行任务
    needs: build  # 确保在构建完成后执行发布

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/*'  # 假设打包后的文件都在 dist 目录中，修改为实际路径
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动提供的 token

